---
title: "Research"
output: html_document
---
<div>

<br/>

## Publications

#### <em> [The Psychosocial Value of Employment: Evidence from a Refugee Camp](pdfs/employment.pdf) </em> 
*(with Erin Kelley, Reshmaan Hussam, and Fatima Tuz Zahra)* 

*Abstract:*
Employment may be an important source of wellbeing beyond its role as a source of income. This paper presents a causal estimate of the psychosocial value of employment in refugee camps in Bangladesh. We engage 745 individuals in a field experiment with three arms: a control arm, a weekly cash arm, and an employment arm of equal value. We find that employment generates improvements in psychosocial wellbeing substantially larger than cash alone. Consistent with these findings, 66% of those in our work treatment are willing to forego cash payments to instead work for free.

*American Economic Review (2022), 112(11)*

<br/>


#### <em> [Adapting to Floods with Guaranteed Credit: Evidence from Bangladesh](pdfs/Adaptation.pdf) </em> 

*Abstract:*
Climate change is increasing the frequency of extreme weather events, with low-income countries being disproportionately impacted. However, these countries often face market frictions that hinder their ability to adopt effective adaptation strategies. In this paper, I explore the role of credit market failures in limiting adaptation. To achieve this, I collaborate with a large micro-finance institution and offer a randomly selected group of farmers access to guaranteed credit through an Emergency Loan following a negative climate shock. I document three key results. First, farmers who have access to the emergency loan make less costly adaptation choices and are less severely affected when a flood occurs. Secondly, I find no evidence of adverse spillover effects on households that did not receive the Emergency Loan. Finally, I demonstrate that providing the Emergency Loan is profitable for the micro-finance institution, making it a viable tool for the private sector to employ in similar circumstances.


*Econometrica (2024), 92(2)*
<br/>
<br/>

#### <em> [Monitoring in Target Contracts: Theory and Experiment in Kenyan Public Transit](pdfs/matatu.pdf) </em>
*(with Erin Kelley and David Sch&ouml;nholzer)*

*Abstract:*
This paper examines whether moral hazard is a meaningful barrier to firm productivity and growth in low-income countries. We introduce monitoring devices into commuter minibuses in Kenya and randomize which minibus owners have access to the data using a novel mobile app. We find that treated vehicle owners modify the terms of the contract to induce higher effort and lower risk-taking from their drivers, resulting in lower firm costs, higher firm productivity, and firm expansion. These results suggest that moral hazard constrains firm productivity, and the proliferation of monitoring technologies could represent a boon for small firms in low-income countries.

*American Economic Review (2024), 114(10)*
<br/>
<br/>

#### <em> [Customer Discrimination in the Workplace: Evidence from Online Sales](pdfs/customer_discrimination.pdf) </em> 
*(with Erin Kelley, Matthew Pecenco, and Edward Rubin)* 

*Abstract:*
Many workers are evaluated on their ability to engage with customers. We measure the impact of gender-based customer discrimination on the productivity of online sales agents in Sub-Saharan Africa. Using a novel framework that randomly varies the gender of names presented to customers without changing worker behavior, we find the assignment of a female-sounding name leads to 50 percent fewer purchases. Customers also lag in responding, are less expressive, and avoid discussing purchases. We show similar results for customers around the world and across workers. Removing customer bias, we find women would be more productive than their male co-workers.

*Forthcoming* Journal of Labor Economics
<br/>
<br/>


#### <em> [Does Gender Tagging Public Works Increase Women's Participation? Experimental Evidence from Haiti, Kenya, and Rwanda](pdfs/gender_tag_pp.pdf) </em> 
*(with Tanay Balantrapu, Paul Christian, Lelys Dinarte-Diaz, Felipe Dunsch, Jonas Heirman, Dahyeon Jeong, Erin Kelley, Florence Kondylis, and John Loeser)* 

*AEA Papers and Proceedings (2025), 115*
<br/>
<br/>



## Working Papers 

#### <em> [The value of forecasts: Experimental evidence from India](pdfs/BKJLS_India_Forecasts.pdf) </em> 
*(with Fiona Burlig, Amir Jina, Erin Kelley, and Harshil Sahai)* 

*Abstract:*
Unpredictable weather makes it challenging for households and firms to make optimal investment decisions. Technologies that reduce these risks are crucial for climate change adaptation. We experimentally evaluate one such technology – an accurate, localized, early monsoon onset forecast – in India, randomizing 250 villages into control, forecast, or insurance. The forecast changes farmers’ beliefs about the coming growing season. In response, forecast farmers adapt their behavior along multiple margins, changing cultivated area, crop choice, farm input expenditure, and oﬀ-farm business. By enabling farmers to tailor their investments to coming
weather, forecasts reduce farmers’ risk exposure and increase aggregate welfare.

*Pre-analysis plan accepted via pre-results review*  at Journal of Development Economics
<br/>
<br/>


#### <em> [Competitive Job Seekers: When Sharing Less Leaves Firms at a Loss](pdfs/Competition_LaborMarkets.pdf) </em> 
*(with Gaurav Chiplunkar and Erin Kelley)* 

*Abstract:*
We use a randomized control trial to study how young job-seekers share informa- tion about jobs within their social network, and its implications for firms. When competition for a job is made salient, we find that job-seekers are: (i) less likely to share information about the job with their peers; and (ii) choose to share it with fewer higher ability peers. This lowers the size and quality of the applicants a firm sees and the hires they make. These results suggest that firms who rely heavily on social networks to disseminate information about jobs may see lower quality applicants than they expected for positions that are deemed more competitive.
<br/>
<br/>

#### <em> [The Value of Safe Driving: Evidence from Kenya's Public Transport Sector](pdfs/matatu_safety.pdf) </em> 
*(with Erin Kelley and David Schoenholzer)*

*Abstract*
Road traffic accidents in poorly regulated public transit is a leading cause of death in low- and middle-income countries. We study how providing information about bus safety to passengers affects the demand and supply of safer public transit. We collect high-frequency measures of safe driving for five firms operating on one of the busiest long-range routes in Kenya, using a newly developed tracking device. We randomize private information to passengers about which firm is the safest choice. We then provide a public signal to both passengers and firms that buses are now being tracked. Treated passengers do not respond to private information at first, but after the introduction of the public signal they substitute strongly towards the safe firm, and some firms provide safer services. We rationalize these effects in a model of heterogeneous firms responding strategically to higher demand for safety due to the public signal. We derive welfare estimates of alternative equilibria, which imply that the welfare effects of information interventions crucially depend on the nature of the market equilibrium.
<br/>
<br/>

#### <em> [Household Preferences for Female Employment: A Field Experiment in Bangladesh](pdfs/HHKL_laborsupply.pdf) </em> 
*(with Yueh-ya Hsu, Reshmaan Hussam, and Erin Kelley)*

*Abstract*
Female labor force participation remains lower than male participation in many settings. Can this be explained by households’ preference for men’s work, and are these preferences malleable? We address this question with a field experiment in a refugee camp setting in Bangladesh, where we randomly offer the same six-week job—under identical conditions—to either the husband or the wife in a household. We find that when women work, their wellbeing improves but their husbands’ does not. When men work, both their own and their wives’ wellbeing improve, along with the health of the relationship and a greater self-reported sense of purpose for both partners. These findings help shed light on why households favor men working over women, which we document through an incentivized labor supply exercise. However, more than a year later, households where women previously worked for us show significantly stronger preferences for female employment, as men update their beliefs about the costs of women working. These results demonstrate that even brief exposure to women’s work can shift household preferences over female employment.

<br/>
<br/>

### Works in Progress

+ *Home: Experimental Evidence on Repatriation Preferences of Refugees (with Erin Kelley and Reshmaan Hussam)*

+ *Flight Risk or Reward? Returns to Credit Between Refugees and Locals (with Erin Kelley and Reshmaan Hussam)*

+ *Online Marketplaces and Reducing Barriers for Small Firms (with Erin Kelley, Matthew Pecenco)*

<br/>
<br/>

### Policy/Media Documents


#### <em> [Which jobs are lost during a lockdown? Evidence from vacancy postings in India](pdfs/CKL_Covid_July2020.pdf) </em>
*(with Gaurav Chiplunkar and Erin Kelley)*

*Abstract:*
We rely on real-time data from India's second largest job portal to study how COVID-19 (and the associated lockdown measures) impacted the Indian labor market. Detailed firm-level vacancy postings on location, industries, occupations and job characteristics allow us to document three facts that suggest a dramatic contraction in hiring, especially for young, less-educated and female job-seekers. First, we observe a substantial decline in the total number of new vacancies posted and the number of firms that post at least one job. Second, we see an increase in jobs that can be completed from home and fewer jobs in occupations that can be easily automated. Finally, we find evidence that certain job-seekers are more affected than others, as employers post fewer entry-level jobs, require higher levels of experience and education, and advertise fewer jobs in female-dominated occupations.
<br/>
<br/>

</div>



